name: Create PR containing updated CHANGELOG.md and release packages to NPM once PR is merged

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions: {} # remove permissions and set explicitly under "permissions:" below
jobs:
  get-image:
    name: Get Docker Image
    runs-on: buildjet-2vcpu-ubuntu-2204
    outputs:
      image: ${{ steps.get-image.outputs.full-image }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - name: Get image tag
        id: get-image
        uses: ./.github/actions/use-deps-image

  release:
    if: github.repository == 'calcom/cal.com' # prevent this action from running on forks
    needs: get-image
    permissions:
      id-token: write # for NPM provenance - developers can verify where and how it was built
      contents: write # to create release by changesets/action below
      pull-requests: write # to create pull request by changesets/action below
      packages: read # to read Docker images from GitHub container registry
    name: Release
    runs-on: buildjet-4vcpu-ubuntu-2204
    container:
      image: ${{ needs.get-image.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --workdir /workspace
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: /workspace
      - uses: ./.github/actions/dangerous-git-checkout
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changesets-version
          publish: yarn changesets-release
          commit: "chore: version packages" # commit message
          title: "chore: version packages" # PR title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VITE_BOOKER_EMBED_OAUTH_CLIENT_ID: ${{ secrets.VITE_BOOKER_EMBED_OAUTH_CLIENT_ID }}
          VITE_BOOKER_EMBED_API_URL: ${{ secrets.VITE_BOOKER_EMBED_API_URL }}
          NEXT_PUBLIC_WEBAPP_URL: ${{ secrets.NEXT_PUBLIC_WEBAPP_URL }}
