name: Check API v2 breaking changes

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check-api-v2-breaking-changes:
    name: Check API v2 breaking changes
    timeout-minutes: 10
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/yarn-install

      - name: Generate Swagger
        working-directory: apps/api/v2
        run: yarn generate-swagger

      - name: Check API v2 breaking changes
        run: |
          docker run --rm \
            -v "$PWD:/work" -w /work \
            tufin/oasdiff:latest \
            breaking \
            https://raw.githubusercontent.com/calcom/cal.com/refs/heads/main/docs/api-reference/v2/openapi.json \
            docs/api-reference/v2/openapi.json \
            --fail-on ERR \
            --err-ignore .github/oasdiff-err-ignore.txt
