name: Check types
on:
  workflow_call:
env:
  NODE_OPTIONS: --max-old-space-size=6144
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
permissions:
  contents: read
jobs:
  check-types:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - uses: ./.github/actions/cache-checkout
      - uses: ./.github/actions/yarn-install
      - name: Show info
        run: node -e "console.log(require('v8').getHeapStatistics())"
      - name: Configure TSC problem matcher
        run: |
          echo "::remove-matcher owner=tsc::"
          echo "::add-matcher::.github/matchers/tsc-absolute.json"
      - name: Run type check
        run: |
          # Workaround for https://github.com/vercel/turbo/issues/4227
          set -o pipefail
          yarn type-check:ci 2>&1 | tee /tmp/type-check-output.log
          TYPE_CHECK_EXIT_CODE=${PIPESTATUS[0]}
          
          if grep -q "FATAL ERROR:.*heap.*out of memory" /tmp/type-check-output.log; then
            echo "::error::Type check failed due to out of memory error"
            exit 1
          fi
          
          exit $TYPE_CHECK_EXIT_CODE
