name: Crowdin Action

on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: crowdin action
        uses: crowdin/github-action@v1.13.0
        with:
          # upload sources
          upload_sources: true
          
          # upload translations (& auto-approve 'em)
          upload_translations_args: '--auto-approve-imported'
          upload_translations: true
          push_translations: true
          
          # download translations
          download_translations: true
          
          # GH config
          commit_message: "New Crowdin translations by Github Action"
          localization_branch_name: main
          create_pull_request: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
