# This is just to test this file
name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build Docs
    permissions:
      contents: read
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - uses: ./.github/actions/cache-checkout
      - name: Cache Docs build
        uses: actions/cache@v4
        id: cache-docs-build
        env:
          cache-name: docs-build
          key-1: ${{ hashFiles('yarn.lock') }}
          key-2: ${{ hashFiles('docs/**.*', '!**/node_modules') }}
        with:
          path: |
            **/docs/**
          key: ${{ env.cache-name }}-${{ env.key-1 }}-${{ env.key-2 }}
      - name: Run build
        if: steps.cache-docs-build.outputs.cache-hit != 'true'
        working-directory: docs
        run: |
          export NODE_OPTIONS="--max_old_space_size=8192"
          npm install -g mintlify@4.2.87
          mintlify dev &
          sleep 5 # Let it run for 5 seconds
          kill $!
        shell: bash
