name: E2E Embed tests and booking flow(for non-embed as well)
on:
  workflow_call:

jobs:
  e2e-embed:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: calendso
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dangerous-git-checkout
      - run: echo 'NODE_OPTIONS="--max_old_space_size=4096"' >> $GITHUB_ENV
      - uses: ./.github/actions/yarn-install
      - uses: ./.github/actions/yarn-playwright-install
      - uses: ./.github/actions/cache-db
      - uses: ./.github/actions/env-read-file
      - uses: ./.github/actions/cache-build
      - name: Run Tests
        run: yarn turbo run embed-tests-update-snapshots:ci --scope=@calcom/embed-react --concurrency=1
      - name: Upload embed-core results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results-core
          path: packages/embeds/embed-core/playwright/results

      - name: Upload embed-react results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results-react
          path: packages/embeds/embed-react/playwright/results
