name: Lint
on:
  workflow_call:
permissions:
  actions: write
  contents: read
  packages: read
jobs:
  get-image:
    name: Get Docker Image
    runs-on: buildjet-2vcpu-ubuntu-2204
    outputs:
      image: ${{ steps.get-image.outputs.full-image }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - name: Get image tag
        id: get-image
        uses: ./.github/actions/use-deps-image

  lint:
    needs: get-image
    runs-on: buildjet-4vcpu-ubuntu-2204
    container:
      image: ${{ needs.get-image.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - name: Run Lint
        run: yarn lint
        continue-on-error: true
