# Workflow for serving app locally & running Meticulous tests against it

name: Meticulous

# Important: The workflow needs to run both on pushes to your main branch and on pull requests.
# It needs to run on your main branch because it'll use the results from the
# base commit of the PR on the main branch to compare against.
on:
  push:
    branches:
      - main
  pull_request: {}
  # Important: We need the workflow to be triggered on workflow_dispatch events,
  # so that Meticulous can run the workflow on the base commit to compare
  # against if an existing workflow hasn't run
  workflow_dispatch: {}

# Important: The workflow needs all the permissions below.
# These permissions are mainly need to post and update the status check and
# feedback comment on your PR. Meticulous wonâ€™t work without them.
permissions:
  actions: write
  checks: write
  contents: read
  discussions: write
  pull-requests: write
  statuses: write

jobs:
  test:
    name: Report diffs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --non-interactive

      - name: Build project
        run: |
          yarn build

      - name: Serve project
        # Notes:
        #
        # 1. Please make sure your serve command listens 0.0.0.0 rather than localhost or 127.0.0.1
        #    (i.e. listens to all requests via all network interfaces rather than just the loopback interface
        #    - see https://stackoverflow.com/a/20778887 for more details)
        # 2. The sleep is often required to ensure your app is readily being served by the time the Meticulous tests start
        run: |
          yarn serve &
          sleep 5

      - name: Run Meticulous tests
        uses: alwaysmeticulous/report-diffs-action@v1
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          app-url: "http://localhost:3000/"