name: "Meta Workflow: Require Conditional Status Checks"
on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: [Crowdin Action]
    types: [completed]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  required-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure All Conditional Checks Have Passed
        uses: blend/require-conditional-status-checks@2022.02.04
        with:
          timeout: 15m
          github-token: ${{ github.token }}
          interval: 20s
          # Question marks aren't working
          # @see https://github.com/blend/require-conditional-status-checks/pull/11
          checks-yaml: |
            - job: lint
              paths:
                - /**/*.jsx
                - /**/*.js
                - /**/*.tsx
                - /**/*.ts
            - job: check-types
              paths:
                - /**/*.tsx
                - /**/*.ts
            - job: e2e
              paths:
                - /apps/web/**
                - /packages/**
            - job: e2e-embed
              paths:
                - /apps/web/**
                - /packages/embeds/**
            - job: test
              paths:
                - /apps/web/**
                - /packages/**
