name: "Welcome new contributors"

on:
  issues:
    types: opened
  pull_request:
    types: opened

permissions:
  pull-requests: write
  issues: write

jobs:
  semantics:
    name: Placeholder Semantics Job
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder Step
        run: echo "This is a placeholder job."

  welcome-message:
    name: Welcoming New Users
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: semantics
    if: github.event.action == 'opened'
    steps:
      - name: Use First Interaction Action
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Thank you for making your first Pull Request and taking the time to improve Cal.com! ‚ù§Ô∏èüéâ
            Feel free to join the conversation at [slack](https://calendso.slack.com/)
          issue-message: | 
            Thank you for opening your first issue. One of our team members will review it as soon as possible.
